services:
  mysql:
    image: mysql:8.0
    container_name: Data_fitness
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitness_datanaly
    ports:
      - "3220:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  generator:
    build: .
    container_name: generator_fitness
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data: